# Generated by Django 4.2 on 2023-04-30 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoriak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=50, verbose_name='nev')),
            ],
        ),
        migrations.CreateModel(
            name='Recept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=50, verbose_name='nev')),
                ('kep_eleresi_ut', models.CharField(max_length=50, verbose_name='kep eleresi ut')),
                ('leiras', models.TextField(verbose_name='leiras')),
                ('hirdetes_datuma', models.DateField(verbose_name='hirdetes datuma')),
                ('kat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.kategoriak', verbose_name='kategoria_id')),
            ],
        ),
    ]
