# Generated by Django 4.2 on 2023-04-30 12:46

from django.db import migrations


def adatok(apps, schema_editor):
    Kategoria = apps.get_model('app', 'Kategoriak')
    kategoriak = ['főétel', 'leves', 'édesség', 'saláta']
    for i in range(len(kategoriak)):
        k = Kategoria(i+1, kategoriak[i])
        k.save()

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(adatok)
    ]


