# Generated by Django 4.2 on 2023-04-30 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_kategoriak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recept',
            name='hirdetes_datuma',
            field=models.DateField(blank=True, null=True, verbose_name='hirdetes datuma'),
        ),
    ]
